import {MigrationInterface, QueryRunner} from "typeorm";

export class ChangedIDTypeToBigInt1637940557435 implements MigrationInterface {
    name = 'ChangedIDTypeToBigInt1637940557435'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "FK_8c08ae439ea48b8fa5efd17c369"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP CONSTRAINT "FK_bbd740a15c421eb047c83f84d77"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP CONSTRAINT "FK_cf5379446c7770ce52819823aa6"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP CONSTRAINT "PK_fd8e31cc54a22af809d3fbf587b"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD CONSTRAINT "PK_fd8e31cc54a22af809d3fbf587b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD "ownerId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP CONSTRAINT "REL_cf5379446c7770ce52819823aa"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP COLUMN "biolinkId"`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD "biolinkId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD CONSTRAINT "UQ_cf5379446c7770ce52819823aa6" UNIQUE ("biolinkId")`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "FK_7392a9c15c525aed526c19a4c5c"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP CONSTRAINT "FK_38b54e7a93cf8a2f000971a61ed"`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP CONSTRAINT "FK_531b91b9ed78f3481ac91659d3e"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP CONSTRAINT "FK_ffa1c558472efd7b6ab029e584e"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "FK_358886f258e623a560b46ff90c0"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "FK_02febfa734c6ab397e3477d9d04"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "FK_d4c935e9f1437f2398b9432464a"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "UQ_286f699402052a53ca1b589caae"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "PK_e8c9c2d68eb099d0f9982a2f3bc"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "PK_e8c9c2d68eb099d0f9982a2f3bc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "REL_8c08ae439ea48b8fa5efd17c36"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "usernameId"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "usernameId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "UQ_8c08ae439ea48b8fa5efd17c369" UNIQUE ("usernameId")`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "categoryId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "REL_d4c935e9f1437f2398b9432464"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "verificationId"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "verificationId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "UQ_d4c935e9f1437f2398b9432464a" UNIQUE ("verificationId")`);
        await queryRunner.query(`ALTER TABLE "public"."black_list" DROP CONSTRAINT "PK_6969ca1c62bdf4fef47a85b8195"`);
        await queryRunner.query(`ALTER TABLE "public"."black_list" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."black_list" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."black_list" ADD CONSTRAINT "PK_6969ca1c62bdf4fef47a85b8195" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "FK_5416fe55dabbd4e366b8e46a5c1"`);
        await queryRunner.query(`ALTER TABLE "public"."category" DROP CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03"`);
        await queryRunner.query(`ALTER TABLE "public"."category" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."category" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."category" ADD CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP CONSTRAINT "FK_18de3e42ff2757efe4f60b6d0b4"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP CONSTRAINT "FK_cb9fad30c77558562dc94bb1689"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP CONSTRAINT "PK_6f27e86fa885f79a58dbcbacb50"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD CONSTRAINT "PK_6f27e86fa885f79a58dbcbacb50" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP COLUMN "chatRoomId"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD "chatRoomId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP CONSTRAINT "FK_f3cc0ca0c4b191410f1e0ab5d21"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP CONSTRAINT "FK_f4e2d3c75df8e871e3ccb63d9ed"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP CONSTRAINT "PK_8aa3a52cf74c96469f0ef9fbe3e"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD CONSTRAINT "PK_8aa3a52cf74c96469f0ef9fbe3e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP CONSTRAINT "REL_f4e2d3c75df8e871e3ccb63d9e"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP COLUMN "lastMessageSentId"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD "lastMessageSentId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD CONSTRAINT "UQ_f4e2d3c75df8e871e3ccb63d9ed" UNIQUE ("lastMessageSentId")`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP CONSTRAINT "FK_3fb14124b42809e57cd35bce0a4"`);
        await queryRunner.query(`ALTER TABLE "public"."code" DROP CONSTRAINT "FK_1d16fe2b4b3993e5a8d26e4909d"`);
        await queryRunner.query(`ALTER TABLE "public"."code" DROP CONSTRAINT "PK_367e70f79a9106b8e802e1a9825"`);
        await queryRunner.query(`ALTER TABLE "public"."code" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."code" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."code" ADD CONSTRAINT "PK_367e70f79a9106b8e802e1a9825" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."code" DROP COLUMN "referrerId"`);
        await queryRunner.query(`ALTER TABLE "public"."code" ADD "referrerId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."domain" DROP CONSTRAINT "FK_dde349027ada546b854e9fdb5fc"`);
        await queryRunner.query(`ALTER TABLE "public"."domain" DROP CONSTRAINT "PK_27e3ec3ea0ae02c8c5bceab3ba9"`);
        await queryRunner.query(`ALTER TABLE "public"."domain" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."domain" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."domain" ADD CONSTRAINT "PK_27e3ec3ea0ae02c8c5bceab3ba9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."domain" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."domain" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "FK_8300048608d8721aea27747b07a"`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP CONSTRAINT "FK_bc096b4e18b1f9508197cd98066"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP CONSTRAINT "FK_550dce89df9570f251b6af2665a"`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP CONSTRAINT "FK_14a562b14bb83fc8ba73d30d3e0"`);
        await queryRunner.query(`ALTER TABLE "public"."referral" DROP CONSTRAINT "FK_fc12cab7df2de5a584c10c57480"`);
        await queryRunner.query(`ALTER TABLE "public"."report" DROP CONSTRAINT "FK_253163ca85b927f62596606f6cc"`);
        await queryRunner.query(`ALTER TABLE "public"."support" DROP CONSTRAINT "FK_0768a9a514d90be0f9d00fd8036"`);
        await queryRunner.query(`ALTER TABLE "public"."token" DROP CONSTRAINT "FK_94f168faad896c0786646fa3d4a"`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" DROP CONSTRAINT "FK_21c46c2b3ab66ef0773e5db3464"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "FK_b046318e0b341a7f72110b75857"`);
        await queryRunner.query(`ALTER TABLE "public"."service" DROP CONSTRAINT "FK_53beaca8ac1de1f5b6a3ff7f492"`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "FK_20981b2b68bf03393c44dd1b9d7"`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP CONSTRAINT "FK_40f6ab3925c167d26e52db93cf0"`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP CONSTRAINT "FK_3a7597c7b3d26470efb7c2395d4"`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP COLUMN "planId"`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD "planId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP COLUMN "adminRoleId"`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD "adminRoleId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP COLUMN "registeredByCodeId"`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD "registeredByCodeId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP CONSTRAINT "PK_fda88bc28a84d2d6d06e19df6e5"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD CONSTRAINT "PK_fda88bc28a84d2d6d06e19df6e5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP COLUMN "followerId"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD "followerId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP COLUMN "followeeId"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD "followeeId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP CONSTRAINT "FK_0bb04d0ddd84ea9304e7beb4824"`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP CONSTRAINT "PK_26206fb7186da72fbb9eaa3fac9"`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD CONSTRAINT "PK_26206fb7186da72fbb9eaa3fac9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP COLUMN "biolinkId"`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD "biolinkId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP CONSTRAINT "PK_ba01f0a3e0123651915008bc578"`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP COLUMN "senderId"`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD "senderId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP COLUMN "chatRoomId"`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD "chatRoomId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "FK_9ad13532f48db4ac5a3b3dd70e5"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "FK_d09d285fe1645cd2f0db811e293"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "FK_fb6e13226928c7ddcf2e1bf6160"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "UQ_d09d285fe1645cd2f0db811e293"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD "orderId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "UQ_d09d285fe1645cd2f0db811e293" UNIQUE ("orderId")`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP COLUMN "planId"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD "planId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "FK_c721e93645fdc15f040096d1eaa"`);
        await queryRunner.query(`ALTER TABLE "public"."service" DROP CONSTRAINT "PK_85a21558c006647cd76fdce044b"`);
        await queryRunner.query(`ALTER TABLE "public"."service" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."service" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."service" ADD CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."service" DROP COLUMN "sellerId"`);
        await queryRunner.query(`ALTER TABLE "public"."service" ADD "sellerId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "PK_1031171c13130102495201e3e20"`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP COLUMN "serviceId"`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD "serviceId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD "buyerId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "UQ_9ad13532f48db4ac5a3b3dd70e5"`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP COLUMN "paymentId"`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD "paymentId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "UQ_9ad13532f48db4ac5a3b3dd70e5" UNIQUE ("paymentId")`);
        await queryRunner.query(`ALTER TABLE "public"."plan" DROP CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3"`);
        await queryRunner.query(`ALTER TABLE "public"."plan" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."plan" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."plan" ADD CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."referral" DROP CONSTRAINT "PK_a2d3e935a6591168066defec5ad"`);
        await queryRunner.query(`ALTER TABLE "public"."referral" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."referral" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."referral" ADD CONSTRAINT "PK_a2d3e935a6591168066defec5ad" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."referral" DROP COLUMN "referredById"`);
        await queryRunner.query(`ALTER TABLE "public"."referral" ADD "referredById" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."report" DROP CONSTRAINT "PK_99e4d0bea58cba73c57f935a546"`);
        await queryRunner.query(`ALTER TABLE "public"."report" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."report" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."report" ADD CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."report" DROP COLUMN "reporterId"`);
        await queryRunner.query(`ALTER TABLE "public"."report" ADD "reporterId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."settings" DROP CONSTRAINT "PK_0669fe20e252eb692bf4d344975"`);
        await queryRunner.query(`ALTER TABLE "public"."settings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."settings" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."settings" ADD CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."support" DROP CONSTRAINT "PK_54c6021e6f6912eaaee36b3045d"`);
        await queryRunner.query(`ALTER TABLE "public"."support" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."support" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."support" ADD CONSTRAINT "PK_54c6021e6f6912eaaee36b3045d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."support" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."support" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."tax" DROP CONSTRAINT "PK_2c1e62c595571139e2fb0e9c319"`);
        await queryRunner.query(`ALTER TABLE "public"."tax" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."tax" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."tax" ADD CONSTRAINT "PK_2c1e62c595571139e2fb0e9c319" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."token" DROP CONSTRAINT "PK_82fae97f905930df5d62a702fc9"`);
        await queryRunner.query(`ALTER TABLE "public"."token" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."token" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."token" ADD CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."token" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."token" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP CONSTRAINT "PK_7d496873aeb9162f01a67967f7b"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD CONSTRAINT "PK_7d496873aeb9162f01a67967f7b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP COLUMN "linkId"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD "linkId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP COLUMN "biolinkId"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD "biolinkId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" DROP CONSTRAINT "PK_773dbba6ad8ad2cdecfef243953"`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" ADD CONSTRAINT "PK_773dbba6ad8ad2cdecfef243953" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "PK_f7e3a90ca384e71d6e2e93bb340"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "PK_f7e3a90ca384e71d6e2e93bb340" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD "userId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "REL_7392a9c15c525aed526c19a4c5"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP COLUMN "biolinkId"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD "biolinkId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "UQ_7392a9c15c525aed526c19a4c5c" UNIQUE ("biolinkId")`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD "categoryId" bigint`);
        await queryRunner.query(`ALTER TABLE "public"."admin_role" DROP CONSTRAINT "PK_fd32421f2d93414e46a8fcfd86b"`);
        await queryRunner.query(`ALTER TABLE "public"."admin_role" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."admin_role" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."admin_role" ADD CONSTRAINT "PK_fd32421f2d93414e46a8fcfd86b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "UQ_286f699402052a53ca1b589caae" UNIQUE ("usernameId", "deletedAt")`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD CONSTRAINT "FK_bbd740a15c421eb047c83f84d77" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD CONSTRAINT "FK_cf5379446c7770ce52819823aa6" FOREIGN KEY ("biolinkId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "FK_8c08ae439ea48b8fa5efd17c369" FOREIGN KEY ("usernameId") REFERENCES "username"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "FK_358886f258e623a560b46ff90c0" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "FK_02febfa734c6ab397e3477d9d04" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "FK_d4c935e9f1437f2398b9432464a" FOREIGN KEY ("verificationId") REFERENCES "verification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD CONSTRAINT "FK_18de3e42ff2757efe4f60b6d0b4" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD CONSTRAINT "FK_cb9fad30c77558562dc94bb1689" FOREIGN KEY ("chatRoomId") REFERENCES "chat_room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD CONSTRAINT "FK_f4e2d3c75df8e871e3ccb63d9ed" FOREIGN KEY ("lastMessageSentId") REFERENCES "message"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."code" ADD CONSTRAINT "FK_1d16fe2b4b3993e5a8d26e4909d" FOREIGN KEY ("referrerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."domain" ADD CONSTRAINT "FK_dde349027ada546b854e9fdb5fc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD CONSTRAINT "FK_40f6ab3925c167d26e52db93cf0" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD CONSTRAINT "FK_3a7597c7b3d26470efb7c2395d4" FOREIGN KEY ("adminRoleId") REFERENCES "admin_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD CONSTRAINT "FK_3fb14124b42809e57cd35bce0a4" FOREIGN KEY ("registeredByCodeId") REFERENCES "code"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD CONSTRAINT "FK_550dce89df9570f251b6af2665a" FOREIGN KEY ("followerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD CONSTRAINT "FK_38b54e7a93cf8a2f000971a61ed" FOREIGN KEY ("followeeId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD CONSTRAINT "FK_14a562b14bb83fc8ba73d30d3e0" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD CONSTRAINT "FK_531b91b9ed78f3481ac91659d3e" FOREIGN KEY ("biolinkId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD CONSTRAINT "FK_bc096b4e18b1f9508197cd98066" FOREIGN KEY ("senderId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD CONSTRAINT "FK_f3cc0ca0c4b191410f1e0ab5d21" FOREIGN KEY ("chatRoomId") REFERENCES "chat_room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "FK_b046318e0b341a7f72110b75857" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "FK_d09d285fe1645cd2f0db811e293" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "FK_fb6e13226928c7ddcf2e1bf6160" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."service" ADD CONSTRAINT "FK_53beaca8ac1de1f5b6a3ff7f492" FOREIGN KEY ("sellerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "FK_c721e93645fdc15f040096d1eaa" FOREIGN KEY ("serviceId") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "FK_20981b2b68bf03393c44dd1b9d7" FOREIGN KEY ("buyerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "FK_9ad13532f48db4ac5a3b3dd70e5" FOREIGN KEY ("paymentId") REFERENCES "payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."referral" ADD CONSTRAINT "FK_fc12cab7df2de5a584c10c57480" FOREIGN KEY ("referredById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."report" ADD CONSTRAINT "FK_253163ca85b927f62596606f6cc" FOREIGN KEY ("reporterId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."support" ADD CONSTRAINT "FK_0768a9a514d90be0f9d00fd8036" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."token" ADD CONSTRAINT "FK_94f168faad896c0786646fa3d4a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD CONSTRAINT "FK_0bb04d0ddd84ea9304e7beb4824" FOREIGN KEY ("linkId") REFERENCES "link"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD CONSTRAINT "FK_ffa1c558472efd7b6ab029e584e" FOREIGN KEY ("biolinkId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" ADD CONSTRAINT "FK_21c46c2b3ab66ef0773e5db3464" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "FK_8300048608d8721aea27747b07a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "FK_7392a9c15c525aed526c19a4c5c" FOREIGN KEY ("biolinkId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "FK_5416fe55dabbd4e366b8e46a5c1" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "FK_5416fe55dabbd4e366b8e46a5c1"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "FK_7392a9c15c525aed526c19a4c5c"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "FK_8300048608d8721aea27747b07a"`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" DROP CONSTRAINT "FK_21c46c2b3ab66ef0773e5db3464"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP CONSTRAINT "FK_ffa1c558472efd7b6ab029e584e"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP CONSTRAINT "FK_0bb04d0ddd84ea9304e7beb4824"`);
        await queryRunner.query(`ALTER TABLE "public"."token" DROP CONSTRAINT "FK_94f168faad896c0786646fa3d4a"`);
        await queryRunner.query(`ALTER TABLE "public"."support" DROP CONSTRAINT "FK_0768a9a514d90be0f9d00fd8036"`);
        await queryRunner.query(`ALTER TABLE "public"."report" DROP CONSTRAINT "FK_253163ca85b927f62596606f6cc"`);
        await queryRunner.query(`ALTER TABLE "public"."referral" DROP CONSTRAINT "FK_fc12cab7df2de5a584c10c57480"`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "FK_9ad13532f48db4ac5a3b3dd70e5"`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "FK_20981b2b68bf03393c44dd1b9d7"`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "FK_c721e93645fdc15f040096d1eaa"`);
        await queryRunner.query(`ALTER TABLE "public"."service" DROP CONSTRAINT "FK_53beaca8ac1de1f5b6a3ff7f492"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "FK_fb6e13226928c7ddcf2e1bf6160"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "FK_d09d285fe1645cd2f0db811e293"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "FK_b046318e0b341a7f72110b75857"`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP CONSTRAINT "FK_f3cc0ca0c4b191410f1e0ab5d21"`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP CONSTRAINT "FK_bc096b4e18b1f9508197cd98066"`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP CONSTRAINT "FK_531b91b9ed78f3481ac91659d3e"`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP CONSTRAINT "FK_14a562b14bb83fc8ba73d30d3e0"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP CONSTRAINT "FK_38b54e7a93cf8a2f000971a61ed"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP CONSTRAINT "FK_550dce89df9570f251b6af2665a"`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP CONSTRAINT "FK_3fb14124b42809e57cd35bce0a4"`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP CONSTRAINT "FK_3a7597c7b3d26470efb7c2395d4"`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP CONSTRAINT "FK_40f6ab3925c167d26e52db93cf0"`);
        await queryRunner.query(`ALTER TABLE "public"."domain" DROP CONSTRAINT "FK_dde349027ada546b854e9fdb5fc"`);
        await queryRunner.query(`ALTER TABLE "public"."code" DROP CONSTRAINT "FK_1d16fe2b4b3993e5a8d26e4909d"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP CONSTRAINT "FK_f4e2d3c75df8e871e3ccb63d9ed"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP CONSTRAINT "FK_cb9fad30c77558562dc94bb1689"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP CONSTRAINT "FK_18de3e42ff2757efe4f60b6d0b4"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "FK_d4c935e9f1437f2398b9432464a"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "FK_02febfa734c6ab397e3477d9d04"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "FK_358886f258e623a560b46ff90c0"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "FK_8c08ae439ea48b8fa5efd17c369"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP CONSTRAINT "FK_cf5379446c7770ce52819823aa6"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP CONSTRAINT "FK_bbd740a15c421eb047c83f84d77"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "UQ_286f699402052a53ca1b589caae"`);
        await queryRunner.query(`ALTER TABLE "public"."admin_role" DROP CONSTRAINT "PK_fd32421f2d93414e46a8fcfd86b"`);
        await queryRunner.query(`ALTER TABLE "public"."admin_role" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."admin_role" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."admin_role" ADD CONSTRAINT "PK_fd32421f2d93414e46a8fcfd86b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD "categoryId" integer`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "UQ_7392a9c15c525aed526c19a4c5c"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP COLUMN "biolinkId"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD "biolinkId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "REL_7392a9c15c525aed526c19a4c5" UNIQUE ("biolinkId")`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP CONSTRAINT "PK_f7e3a90ca384e71d6e2e93bb340"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "PK_f7e3a90ca384e71d6e2e93bb340" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" DROP CONSTRAINT "PK_773dbba6ad8ad2cdecfef243953"`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" ADD CONSTRAINT "PK_773dbba6ad8ad2cdecfef243953" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP COLUMN "biolinkId"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD "biolinkId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP COLUMN "linkId"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD "linkId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP CONSTRAINT "PK_7d496873aeb9162f01a67967f7b"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD CONSTRAINT "PK_7d496873aeb9162f01a67967f7b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."token" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."token" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."token" DROP CONSTRAINT "PK_82fae97f905930df5d62a702fc9"`);
        await queryRunner.query(`ALTER TABLE "public"."token" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."token" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."token" ADD CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."tax" DROP CONSTRAINT "PK_2c1e62c595571139e2fb0e9c319"`);
        await queryRunner.query(`ALTER TABLE "public"."tax" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."tax" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."tax" ADD CONSTRAINT "PK_2c1e62c595571139e2fb0e9c319" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."support" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."support" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."support" DROP CONSTRAINT "PK_54c6021e6f6912eaaee36b3045d"`);
        await queryRunner.query(`ALTER TABLE "public"."support" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."support" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."support" ADD CONSTRAINT "PK_54c6021e6f6912eaaee36b3045d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."settings" DROP CONSTRAINT "PK_0669fe20e252eb692bf4d344975"`);
        await queryRunner.query(`ALTER TABLE "public"."settings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."settings" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."settings" ADD CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."report" DROP COLUMN "reporterId"`);
        await queryRunner.query(`ALTER TABLE "public"."report" ADD "reporterId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."report" DROP CONSTRAINT "PK_99e4d0bea58cba73c57f935a546"`);
        await queryRunner.query(`ALTER TABLE "public"."report" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."report" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."report" ADD CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."referral" DROP COLUMN "referredById"`);
        await queryRunner.query(`ALTER TABLE "public"."referral" ADD "referredById" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."referral" DROP CONSTRAINT "PK_a2d3e935a6591168066defec5ad"`);
        await queryRunner.query(`ALTER TABLE "public"."referral" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."referral" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."referral" ADD CONSTRAINT "PK_a2d3e935a6591168066defec5ad" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."plan" DROP CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3"`);
        await queryRunner.query(`ALTER TABLE "public"."plan" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."plan" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."plan" ADD CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "UQ_9ad13532f48db4ac5a3b3dd70e5"`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP COLUMN "paymentId"`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD "paymentId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "UQ_9ad13532f48db4ac5a3b3dd70e5" UNIQUE ("paymentId")`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD "buyerId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP COLUMN "serviceId"`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD "serviceId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP CONSTRAINT "PK_1031171c13130102495201e3e20"`);
        await queryRunner.query(`ALTER TABLE "public"."order" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."service" DROP COLUMN "sellerId"`);
        await queryRunner.query(`ALTER TABLE "public"."service" ADD "sellerId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."service" DROP CONSTRAINT "PK_85a21558c006647cd76fdce044b"`);
        await queryRunner.query(`ALTER TABLE "public"."service" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."service" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."service" ADD CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "FK_c721e93645fdc15f040096d1eaa" FOREIGN KEY ("serviceId") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP COLUMN "planId"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD "planId" integer`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "UQ_d09d285fe1645cd2f0db811e293"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD "orderId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "UQ_d09d285fe1645cd2f0db811e293" UNIQUE ("orderId")`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "FK_fb6e13226928c7ddcf2e1bf6160" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "FK_d09d285fe1645cd2f0db811e293" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "FK_9ad13532f48db4ac5a3b3dd70e5" FOREIGN KEY ("paymentId") REFERENCES "payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP COLUMN "chatRoomId"`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD "chatRoomId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP COLUMN "senderId"`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD "senderId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP CONSTRAINT "PK_ba01f0a3e0123651915008bc578"`);
        await queryRunner.query(`ALTER TABLE "public"."message" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP COLUMN "biolinkId"`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD "biolinkId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP CONSTRAINT "PK_26206fb7186da72fbb9eaa3fac9"`);
        await queryRunner.query(`ALTER TABLE "public"."link" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD CONSTRAINT "PK_26206fb7186da72fbb9eaa3fac9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD CONSTRAINT "FK_0bb04d0ddd84ea9304e7beb4824" FOREIGN KEY ("linkId") REFERENCES "link"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP COLUMN "followeeId"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD "followeeId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP COLUMN "followerId"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD "followerId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP CONSTRAINT "PK_fda88bc28a84d2d6d06e19df6e5"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD CONSTRAINT "PK_fda88bc28a84d2d6d06e19df6e5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP COLUMN "registeredByCodeId"`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD "registeredByCodeId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP COLUMN "adminRoleId"`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD "adminRoleId" integer`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP COLUMN "planId"`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD "planId" integer`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "public"."user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD CONSTRAINT "FK_3a7597c7b3d26470efb7c2395d4" FOREIGN KEY ("adminRoleId") REFERENCES "admin_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD CONSTRAINT "FK_40f6ab3925c167d26e52db93cf0" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."order" ADD CONSTRAINT "FK_20981b2b68bf03393c44dd1b9d7" FOREIGN KEY ("buyerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."service" ADD CONSTRAINT "FK_53beaca8ac1de1f5b6a3ff7f492" FOREIGN KEY ("sellerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."payment" ADD CONSTRAINT "FK_b046318e0b341a7f72110b75857" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."user_logs" ADD CONSTRAINT "FK_21c46c2b3ab66ef0773e5db3464" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."token" ADD CONSTRAINT "FK_94f168faad896c0786646fa3d4a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."support" ADD CONSTRAINT "FK_0768a9a514d90be0f9d00fd8036" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."report" ADD CONSTRAINT "FK_253163ca85b927f62596606f6cc" FOREIGN KEY ("reporterId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."referral" ADD CONSTRAINT "FK_fc12cab7df2de5a584c10c57480" FOREIGN KEY ("referredById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD CONSTRAINT "FK_14a562b14bb83fc8ba73d30d3e0" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD CONSTRAINT "FK_550dce89df9570f251b6af2665a" FOREIGN KEY ("followerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD CONSTRAINT "FK_bc096b4e18b1f9508197cd98066" FOREIGN KEY ("senderId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "FK_8300048608d8721aea27747b07a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."domain" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."domain" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."domain" DROP CONSTRAINT "PK_27e3ec3ea0ae02c8c5bceab3ba9"`);
        await queryRunner.query(`ALTER TABLE "public"."domain" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."domain" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."domain" ADD CONSTRAINT "PK_27e3ec3ea0ae02c8c5bceab3ba9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."domain" ADD CONSTRAINT "FK_dde349027ada546b854e9fdb5fc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."code" DROP COLUMN "referrerId"`);
        await queryRunner.query(`ALTER TABLE "public"."code" ADD "referrerId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."code" DROP CONSTRAINT "PK_367e70f79a9106b8e802e1a9825"`);
        await queryRunner.query(`ALTER TABLE "public"."code" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."code" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."code" ADD CONSTRAINT "PK_367e70f79a9106b8e802e1a9825" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."code" ADD CONSTRAINT "FK_1d16fe2b4b3993e5a8d26e4909d" FOREIGN KEY ("referrerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."user" ADD CONSTRAINT "FK_3fb14124b42809e57cd35bce0a4" FOREIGN KEY ("registeredByCodeId") REFERENCES "code"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP CONSTRAINT "UQ_f4e2d3c75df8e871e3ccb63d9ed"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP COLUMN "lastMessageSentId"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD "lastMessageSentId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD CONSTRAINT "REL_f4e2d3c75df8e871e3ccb63d9e" UNIQUE ("lastMessageSentId")`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP CONSTRAINT "PK_8aa3a52cf74c96469f0ef9fbe3e"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD CONSTRAINT "PK_8aa3a52cf74c96469f0ef9fbe3e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room" ADD CONSTRAINT "FK_f4e2d3c75df8e871e3ccb63d9ed" FOREIGN KEY ("lastMessageSentId") REFERENCES "message"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."message" ADD CONSTRAINT "FK_f3cc0ca0c4b191410f1e0ab5d21" FOREIGN KEY ("chatRoomId") REFERENCES "chat_room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP COLUMN "chatRoomId"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD "chatRoomId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP CONSTRAINT "PK_6f27e86fa885f79a58dbcbacb50"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD CONSTRAINT "PK_6f27e86fa885f79a58dbcbacb50" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD CONSTRAINT "FK_cb9fad30c77558562dc94bb1689" FOREIGN KEY ("chatRoomId") REFERENCES "chat_room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."chat_room_to_user" ADD CONSTRAINT "FK_18de3e42ff2757efe4f60b6d0b4" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."category" DROP CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03"`);
        await queryRunner.query(`ALTER TABLE "public"."category" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."category" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."category" ADD CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "FK_5416fe55dabbd4e366b8e46a5c1" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."black_list" DROP CONSTRAINT "PK_6969ca1c62bdf4fef47a85b8195"`);
        await queryRunner.query(`ALTER TABLE "public"."black_list" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."black_list" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."black_list" ADD CONSTRAINT "PK_6969ca1c62bdf4fef47a85b8195" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "UQ_d4c935e9f1437f2398b9432464a"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "verificationId"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "verificationId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "REL_d4c935e9f1437f2398b9432464" UNIQUE ("verificationId")`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "categoryId" integer`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "UQ_8c08ae439ea48b8fa5efd17c369"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "usernameId"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "usernameId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "REL_8c08ae439ea48b8fa5efd17c36" UNIQUE ("usernameId")`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP CONSTRAINT "PK_e8c9c2d68eb099d0f9982a2f3bc"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "PK_e8c9c2d68eb099d0f9982a2f3bc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "UQ_286f699402052a53ca1b589caae" UNIQUE ("deletedAt", "usernameId")`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "FK_d4c935e9f1437f2398b9432464a" FOREIGN KEY ("verificationId") REFERENCES "verification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "FK_02febfa734c6ab397e3477d9d04" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "FK_358886f258e623a560b46ff90c0" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."track_link" ADD CONSTRAINT "FK_ffa1c558472efd7b6ab029e584e" FOREIGN KEY ("biolinkId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."link" ADD CONSTRAINT "FK_531b91b9ed78f3481ac91659d3e" FOREIGN KEY ("biolinkId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."follow" ADD CONSTRAINT "FK_38b54e7a93cf8a2f000971a61ed" FOREIGN KEY ("followeeId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."verification" ADD CONSTRAINT "FK_7392a9c15c525aed526c19a4c5c" FOREIGN KEY ("biolinkId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP CONSTRAINT "UQ_cf5379446c7770ce52819823aa6"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP COLUMN "biolinkId"`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD "biolinkId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD CONSTRAINT "REL_cf5379446c7770ce52819823aa" UNIQUE ("biolinkId")`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD "ownerId" uuid`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP CONSTRAINT "PK_fd8e31cc54a22af809d3fbf587b"`);
        await queryRunner.query(`ALTER TABLE "public"."username" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD CONSTRAINT "PK_fd8e31cc54a22af809d3fbf587b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD CONSTRAINT "FK_cf5379446c7770ce52819823aa6" FOREIGN KEY ("biolinkId") REFERENCES "biolink"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."username" ADD CONSTRAINT "FK_bbd740a15c421eb047c83f84d77" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."biolink" ADD CONSTRAINT "FK_8c08ae439ea48b8fa5efd17c369" FOREIGN KEY ("usernameId") REFERENCES "username"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
